config/routes.rb
Rails.application.routes.draw do
  

  root 'posts#index'

  get 'posts/blastoff'

  get 'sessions/new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users

  delete "users/:id" => "users#destroy", as: :delete_user_path
  
  resources :categories

  resources :posts do
    member do
      post 'vote'
    end 

    collection do
      get 'archives'
    end 

    resources :comments do
      post 'vote'
    end

    resources :donations do 
      post 'donate'
    end  
      
  end 

   

end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :posts
	has_many :comments
	has_many :votes
	has_many :donations

	def self.from_omniauth(auth)
		user = find_or_create_by(uid: auth['uid'], provider: auth['provider'])
		user.provider = auth.provider
		user.uid = auth.uid
		user.name = auth.info.name
		user.image_url = auth.info.image
		user.oauth_token = auth.credentials.token
		user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    	user.save!
    	user
  	end  

  	def total_user_votes
  		self.posts.map{|a| a.total_votes.to_i}.sum	
  	end

  	def user_funds
		
		@funds= self.posts.each do |p|
					p.donations.map
				end	
		@funds.amount.sum		
	end	
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all.sort_by{|x| x.total_user_votes}.reverse
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all.sort_by{|x| x.total_votes}.reverse
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :organization, :uid, :provider, :oauth_token, :oauth_expires_at, :image_url)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :organization %><br>
    <%= f.text_field :organization %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :oauth_token %><br>
    <%= f.text_field :oauth_token %>
  </div>
  <div class="field">
    <%= f.label :oauth_expires_at %><br>
    <%= f.datetime_select :oauth_expires_at %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="banner">
  <%= image_tag @user.image_url, class:"userShowImg" %>
  <h2 class="userShowName">
    <%= @user.name %>
  </h2>
</div> 

<% if ((@user.id == current_user.id) || (current_user.name == "Michael McCready")) %> 
	<%= form_for(@user) do |f| %>
	  <% if @user.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

	      <ul>
	      <% @user.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	  	<div class="row">
			  <div class="field">
			    <%= f.label :organization %><br>
			    <%= f.text_field :organization %>
			  </div>
			  <div class="field">
			    <%= f.label :image_url %><br>
			    <%= f.text_field :image_url %>
			  </div>
			  <div class="actions">
			    <%= f.submit %>
			  </div>
			  <%= link_to "Delete Profile", user_path, method: :delete, data: {   confirm: "Are you sure you want to delete this profile?"} %></br>
		  </div>
	<% end %>
<% end %>

<%= link_to 'Back to Users', users_path %>

app/views/users/index.html.erb
<h1>Contributors</h1>

<% @users.each do |user| %>
  <div class="row">
    <div class="small-11 columns">
      <div id="userIndexThumb" style="background-image: url(<%= user.image_url %>)"></div>
      <div class="indexName">
        <h4><%= link_to user.name, user %></h4>
        <% if user.organization != nil %>
          <%= user.organization.upcase %>
         <% end %> 
      </div>
    </div>
    <% if user.total_user_votes != nil %>
  		<% user.total_user_votes %>
		<% end %>  
    <% if ((user.id == current_user.id) || (current_user.name == "Michael McCready")) %>  
	    <div class="small-1 columns">
	    	<%= link_to 'Edit', edit_user_path(user) %>
	    </div>    
    <% end %> 
  </div>
<% end %>




 
<%#= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div id="banner">
  <div class="userShowImg" style="background-image: url(<%= @user.image_url %>)"></div>
  <%#= image_tag @user.image_url, class:"userShowImg" %>
  <h2 class="userShowName">
    <%= @user.name %>
  </h2>
</div> 
<% if @user.organization != nil %> 
<p class="orgShow">
  <%= @user.organization.upcase %>
</p>
<% end %>
<div class="userStats">
  <h4>Vote Balance <%= @user.total_user_votes %></h4>
  <!-- <h4>Total Donations $<%#= @user.user_funds %></h4> -->
</div>

<% @posts.each do |post| %>
  <div class="row" id="post">
    <div class="small-12 columns" id="postImg" style="background-image: url(<%= post.image.url %>)">
      <div id="idTag">
        <%= image_tag post.user.image_url, class:"small-2 columns", id:"userThumb" %>
        <div id="posterName">
          <%= post.user.name %>
        </div>
      </div>

      <div class="postVote">
        <%= post.total_votes %> votes
      </div>

      <div class="small-12 columns" id="postTag">
        <strong><%= link_to post.title, post, style:"color: white" %></strong><br>
        <%= post.description[0,60]%>..
      </div>
    </div>
    <h5 class="small-3 columns moreButton"><%= link_to "More", post %></h5>
     <div class="small-9 columns indexVote">
      <!-- votes control -->
      <div class="vote upVote">
        <%#= post.up_votes %>
        <%= link_to vote_post_path(post, vote: true), method: 'post' do %>
          <h2>+</h2>
        <% end %> 
      </div>  
      <div class="vote downVote">
        <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
          <h2>-</h2>
        <% end %> 
      </div> 
    </div>  
  </div>  
<% end %>