config/routes.rb
Rails.application.routes.draw do
  

  root 'posts#index'

  get 'posts/blastoff'

  get 'sessions/new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users

  delete "users/:id" => "users#destroy", as: :delete_user_path
  
  resources :categories

  resources :posts do
    member do
      post 'vote'
    end 

    collection do
      get 'archives'
    end 

    resources :comments do
      post 'vote'
    end

    resources :donations do 
      post 'donate'
    end  
      
  end 

   

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	belongs_to :category
	has_many :comments
	has_many :votes, as: :voteable
	has_many :donations

	has_attached_file :image, styles: { thumb: "32x32", small: "64x64", med: "100x100", large: "200x200", banner: "1200x300" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	def total_votes
		self.up_votes - self.down_votes
	end
	
	def up_votes
		self.votes.where(vote: true).size
	end	

	def down_votes
		self.votes.where(vote: false).size
	end	

	def funds
		# self.donations.sum(:amount)
		self.donations.map{|a| a.amount.to_i}.sum/100
	end	

	def self.search(search)
  		#where("user_name ilike ?", "%#{query}%") 
   		where('title ilike :search OR description ilike :search', search: "%#{search}%")
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index

    if params[:search].present?
      @posts = Post.search params[:search]      
    else
      @posts = Post.all.sort_by{|x| x.total_votes}.reverse
    end  
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def blastoff
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end  

  def vote
    @post = Post.find(params[:id])
    vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])
      if vote.valid?
        flash[:notice] = "Your vote was counted."
      else
        flash[:error] = "You can only vote once."
      end
    redirect_to :back    
  end  

    def donate
    # Amount in cents
    @amount = 500


    @post = Post.find(params[:id])
    @donation = Donation.create(user: current_user, amount: @amount, post_id: @post.id, poster_id: @post.user_id)
      if @donation.valid?
        @donation.save
      end
  

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
    redirect_to charges_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :user_id, :category_id, :post_url)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="comment">
  <%= simple_format h(comment.body) %>
  <%= link_to 'Destroy Comment', comment,
    :confirm => 'Are you sure?',
    :method => :delete if logged_in? %>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose category"} %>
  </div>
  <div class="field">
    <%= f.label :post_url %><br>
    <%= f.text_field :post_url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/blastoff.html.erb
kj

app/views/posts/donations.html.erb
<%= form_tag charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!-- <div class="row" id="banner">
  <h1>SUM OF THE PARTS</h1>
</div>  --> 

<h1>SUM OF THE PARTS</h1>

<% @posts.each do |post| %>
  <div class="row" id="post">
    <div class="small-12 columns" id="postImg" style="background-image: url(<%= post.image.url %>)">
      <div id="idTag">
        <%= image_tag post.user.image_url, class:"small-2 columns", id:"userThumb" %>
        <div id="posterName">
          <%= link_to post.user.name, user_path(post.user), style:"color: white" %>
        </div>
      </div>
      <div class="postVote">
        <%= post.total_votes %> votes
      </div>
      <div class="small-12 columns" id="postTag">
        <strong><%= link_to post.title, post, style:"color: white" %></strong><br>
        <%= post.description[0,70]%>..
      </div>
    </div>
    <h5 class="small-3 columns moreButton"><%= link_to "Details", post %></h5>
    <div class="small-9 columns indexVote">
      <!-- votes control -->
        <%#= post.up_votes %>
      <%= link_to vote_post_path(post, vote: true), class:"vote upVote", method: 'post' do %>
        <h2>+</h2>
      <% end %> 

      <%= link_to vote_post_path(post, vote: false), class:"vote downVote",method: 'post' do %>
        <h2>-</h2>
      <% end %> 
    </div>  
  </div>  
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  <div class="row" id="post">
    <h2 class="small-12 columns showTitle"><%= @post.title %>
      <%= link_to "", "#{@post.post_url}", class:"fa fa-link", target: "_blank" %>
    </h2>
    <div class="row">
      <%= image_tag @post.image, class:"showImage" %>
      <%= @postVotes %>
    </div>  
    
    <div class="row">
      <h5 class="showVotes small-7 columns"><%= @post.total_votes %> VOTES</h5>
      <div class="small-5 columns indexVote">
        <!-- votes control -->
        <%= link_to vote_post_path(@post, vote: true), class:"vote upVote", method: 'post' do %>
          <h2>+</h2>
        <% end %> 

        <%= link_to vote_post_path(@post, vote: false), class:"vote downVote",method: 'post' do %>
          <h2>-</h2>
        <% end %> 
      </div>
    </div>
    <div class="row">
      <%= image_tag @post.user.image_url, id:"userBigThumb" %>
      <div id="posterNameDark">
        <%= link_to @post.user.name.upcase, user_path(@post.user) %>
      </div>
    </div>         
    <div class="row">
      <p class="small-12 columns descriptShow">
        <%= @post.description %>
      </p>  
      <!-- donate section -->
      <div class="small-12 columns fundsShow">
        <h3>FUNDS RAISED</h3>
        <div class="fundCircle">
           <h1>$<%= @post.funds %></h1>
        </div>
      </div> 
      <%= form_tag post_donations_path(@post), id: 'chargeForm' do %>
        <%= hidden_field_tag 'stripeToken' %>
        <%= hidden_field_tag 'stripeEmail' %>
        <div id="customButton" class="donateBtn small-12 columns">Donate</div>
         <script>
            var handler = StripeCheckout.configure({
            key: "<%= Rails.configuration.stripe[:publishable_key] %>",
            image: '',
            token: function(token, args) {
                  document.getElementById("stripeToken").value = token.id;                              
                  document.getElementById("stripeEmail").value = token.email;
                  document.getElementById("chargeForm").submit();
                }
              });

            document.getElementById('customButton').addEventListener('click', function(e) {
              // Open Checkout with further options
              handler.open({
                name: 'SOTPS',
                description: 'Donate',
                amount: 5*100,
              });
              e.preventDefault();
            });
          </script> 
      <% end %>
    </div>
  </div>

 <!-- comment section -->

  <% if current_user %>
    <%= form_for([@post, @post.comments.build]) do |f| %>
      <%= f.text_field :body, placeholder:"Comment", class:"small-12 columns" %>
    <% end %>
  <% else %>
    <%= link_to "Sign in to comment", "/auth/facebook" %>
  <% end %><br><br>

<% @post.comments.all.sort_by{|x| x.total_votes}.reverse.each do |comment| %>
  <div class="row"> 
    <!-- comments -->
    <div class="small-7 columns">
      <%= image_tag comment.user.image_url, id:"logThumb" %>
      <strong><%= link_to comment.user.name, user_path %></strong>
    </div>  
    <div id="voteControls" class="small-5 columns right">
        <div class="vote upVote">
          <%#= post.up_votes %>
          <%= link_to post_comment_vote_path(comment.post, comment, vote: true), method: 'post' do %>
            <h3>+</h3>
          <% end %>
        </div>      
        <div class="vote downVote">
          <%#= post.up_votes %>
          <%= link_to post_comment_vote_path(comment.post, comment, vote: false), method: 'post' do %>
            <h3>-</h3>
          <% end %>
        </div>  
      </div>
      <p class="small-7 columns"><%= comment.body %></p>
      <p class="small-5 columns right comment-body"><%= comment.total_votes %> backers</p> 
</div>  
<% end %>
 
<!-- if user is signed in allow new comment -->