config/routes.rb
Rails.application.routes.draw do
  

  root 'posts#index'

  get 'posts/blastoff'

  get 'sessions/new'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users

  delete "users/:id" => "users#destroy", as: :delete_user_path
  
  resources :categories

  resources :posts do
    member do
      post 'vote'
    end 

    collection do
      get 'archives'
    end 

    resources :comments do
      post 'vote'
    end

    resources :donations do 
      post 'donate'
    end  
      
  end 

   

end

app/views/layouts/_nav.html.erb
<nav class="hide-for-large-up">
<% if current_user %>
	<%= image_tag current_user.image_url, id:"logThumb" %>
<% end %>

<h2 id="menuHead">SOTPS</h2>

<% if current_user %>
	<nav>
		<h3 id="navTop">Menu</h3>
		<div id="menuToggle">
  			<div class="row"><strong>Hi <%= current_user.name %></strong></div>
  			<div class="row"><%= link_to 'Main', posts_path %></div>
  			<div class="row"><%= link_to 'New Post', new_post_path %></div>
  			<div class="row"><%= link_to "Categories", categories_path %></div>
  			<div class="row"><%= link_to "Sign Out", signout_path, id: "sign_out" %></div>
			</div>
	</nav>		
<% else %>
	<h4 id="signIN"><%= link_to "Sign in with Facebook", "/auth/facebook" %>
	</h4>
<% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SOTPS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <script src="https://checkout.stripe.com/checkout.js"></script>
  <script src="//use.typekit.net/xnp0tbe.js"></script>
  <script>try{Typekit.load();}catch(e){}</script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= csrf_meta_tags %>
</head>
<body>

	<%# render "/nav" %>
	<nav class="hide-for-large-up">
		<% if current_user %>
			<%= image_tag current_user.image_url, id:"logThumb" %>
	  	<%= form_tag posts_path, class:"hide-for-large-up", :method => :get do %>
			<%= text_field_tag :search, params[:search], class:"smallSearch small-8 columns", placeholder: "Search posts" %>
		<% end %>

		<nav>
			<h3 id="navTop"><i class="fa fa-bars"></i></h3>
			<div id="menuToggle" class="row">
	  			<div class="row">
	  				<strong><%= current_user.name %></strong>
	  			</div>
	  			<div class="row"><%= link_to 'Main', posts_path %></div>
	  			<div class="row">
	  				<%= link_to 'New Post', new_post_path %>
	  			</div>
	  			<div class="row">
	  				<%= link_to "Categories", categories_path %>
	  			</div>
	  			<!-- <div class="row">
	  				<%#= link_to "Contributers", users_path %>
	  			</div> -->
	  			<div class="row">
	  				<%= link_to "Sign Out", signout_path, id: "sign_out" %>
	  			</div>
			</div>
		</nav>		
		<% else %>
			<h4 id="signIN">
				<strong class="fa fa-facebook-official"></strong>
				<%= link_to " Sign in", "/auth/facebook" %>
			</h4>
		<% end %>
	</nav>

	<div class="large-9 columns">
		<div class="mainWrap">
			<%= yield %>
		</div>	
	</div>	

	<nav class="show-for-large-up large-3 large-offset-9 columns" id="side-nav">
		<div class="row menuLogo"><h2>SOTPS</h2></div>
		<% if current_user %>
			<%= image_tag current_user.image_url, id:"logThumb" %>
		<% end %>


		<% if current_user %>
	  		<strong><%= current_user.name %></strong>
	  		<div class="row">
		  		<div class="row"><%= link_to 'Main', posts_path %></div>
		  		<div class="row"><%= link_to 'New Post', new_post_path %></div>
		  		<div class="row"><%= link_to "Categories", categories_path %></div>
		  		<!-- <div class="row"><%#= link_to "Contributers", users_path %></div> --><hr>
		  		<div class="row"><%= link_to "Sign Out", signout_path, id: "sign_out" %></div><hr>
		  		<%= form_tag posts_path, :method => :get do %>
    				<%= text_field_tag :search, params[:search], placeholder: "Search posts" %>
				<% end %>
		  	</div>			
		<% else %>
			<h4 id="signinExt">
				<strong class="fa fa-facebook-official"></strong>
				<%= link_to "Sign in with Facebook", "/auth/facebook" %>
			</h4>
		<% end %>
	</nav>

</body>
<footer class="visible-for-small-only">
</footer>
</html>